/**
 * Created by jzheng on 1/24/17.
 */
public class Vigenere {
    public static void main(String[] args) {
        String code = "KEBXZSTFUHWCWHQYYKMCSBBCYAIPQVGBNUGLLXMSJJTPACAXTLGJFSHTBJJOUFCIJXVRHFPTXIXFPTHLKGQIAKJRHUSMRNIVYZJNPROFQIEMLIOBLLODFHQCWRTKHNVSEHLQKMBNFJKPEZYVTISCUWSNFKEDAHFOUAPUBBZJMBWKFLXGZRNSAFMXWYAEYYAHBMKHTTGAKNMFKGNXKWBVRPUBBZJAHNWADTGZKHXYRMWSVEKKGHAQUCOCPCAUTHGCZLTWHCFACKYPSQZZKCJXHBVVOESCIDTHTVYCPMZGETXJAWSXNRCJRDYHNVAEWYTSHBVCEKDNBZRICZGVKJPRPKCTGGOOTNAFMTWCGKJFVHJKINBLLBARJBUVBPLSXZEHVDVWBNNZVQLAWRVRTQCKLNHTVYCPFSXZCPUYZYZGRPKRWTHGEYCLUBSCYFJRBIHPKRPEYMDWIVLVYCEXCVCEHLCALFGCCTRITLXVSXZRIFHYRUGCRBORCYIOCJGXNBPKCPIOXKYALBBGUOAKKGKXZGNSIOCQFYIYGIYQESGTTHIWXSWFVCDCCMRKJIVUCLLTYAFJCAYUUMEGUKMFYCAORQHTQNLSTARASRYEKTYCIOZIIDAQIVMYEGURDTDUCIIPAIDNXRQCMVRQGCLTKPMHZVYKTYCBGSKHPACUHMUFKQCSVWBZCSBRGNNLGWVYCWCVGOHPRQGSNBEFPGNDZZOCMYVUDFHZLPXXGGEDPYGALTWECTW";

        IC Incidence = new IC();
        String[] keyArray = new String[7];
        for (int i = 12; i <= 18; ++i) {
            int index = 0;
            StringBuffer Test = new StringBuffer(code.length()/i);
            while (index < code.length()) {
                Test.append(code.charAt(index));
                index += i;
            }
            keyArray[i-12] = Test.toString();
        }

        for (int j = 0; j < 7; ++j) {
            System.out.println(Incidence.calculate(keyArray[j]));
            System.out.println(j + 12);
        }
    }














}
